# Logger
logLevel: info # values: error, warning, info, debug
logType: console # values: console, json
# Fabric
profilePath: "profilePath" # path to Fabric connection profile
userName: "userName" # Fabric user

# Listen section
listenAPI:
  accessToken: ea135929105c4f29a0f5117d2980926f # Bearer token
  addressHTTP: localhost:5678 # the address and port for HTTP that will be open to receive connections
  addressGRPC: localhost:1234 # the address and port for GRPC that will be open to receive connections

# Web server port
# Endpoints:
# /        - liveness probe
# /metrics - prometheus metrics
# /ready   - readiness probe
service:
  address: 3001

# Service options
options:
  batchTxPreimagePrefix: batchTransactions
  collectorsBufSize: 1 # buffer size of blockData
  executeTimeout: 0s # timeout of invoke HLF SDK method
  retryExecuteAttempts: 3 # number of attempts querying the HLF
  retryExecuteMaxDelay: 2s # delay between attempts querying the HLF
  retryExecuteDelay: 500ms # delay between attempts querying the HLF
  ttl: 10800s # time to live of transfer
  transfersInHandleOnChannel: 50 # the number of transfers currently being processed in the channel
  newestRequestStreamBufferSize: 50 # size of the request buffer of creating transfers

# channels for transfer
channels:
  - ch1
  - ch2
  - ch3

#cryptoSrc: local # values: local, vault, google

#vaultCryptoSettings: # HashiCorp Vault configuration
#  vaultToken: 123                     # access token for Vault
#  useRenewableVaultTokens: false
#  vaultAddress: http://localhost:8200 # Vault instance address
#  vaultAuthPath:                      # to which endpoint to send requests to get a temporary Vault token
#  vaultRole:                          # Vault role
#  vaultServiceTokenPath:              # path to the token file for accessing the k8s
#  vaultNamespace: kv/                 # directory where all crypto materials are located in Vault
#  userCert: backend@MSP-cert.pem # Fabric user's cert

googleCryptoSettings: # Google KMS configuration
  gcloudProject: # GCloud project ID
  gcloudCreds:   # path to GCloud credentials
  userCert:      # Fabric user's cert

# Redis configuration
redisStorage:
  addr: # addresses
    - 127.0.0.1:6379
    - 127.0.0.1:6380
  password: 12345 # password
  dbPrefix: transfer # db prefix
  afterTransferTTL: 3600s # time to life after transfer


# Prometheus configuration
promMetrics:
  prefix: transfer # Prometheus prefix without _

